name: Build output PDF

on:
  push:
    branches:
    - main
  workflow_dispatch:
  
jobs:
  default:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build PDF
      run: |
        mkdir ./output
        sudo apt-get install -y texlive-base
        tlmgr install koma-script adjustbox babel-german background bidi collectbox csquotes everypage filehook footmisc footnotebackref framed fvextra letltxmacro ly1 mdframed mweights needspace pagecolor sourcecodepro sourcesanspro titling ucharcat ulem unicode-math upquote xecjk xurl zref hardwrap catchfile
        make README.pdf
    - uses: actions/upload-artifact@master
      with:
        name: output
        path: output    
