name: Build output PDF

on:
  push:
    branches:
    - main
  workflow_dispatch:
  
jobs:
  default:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup TeX Live
      uses: teatimeguest/setup-texlive-action@v2
      with:
        package-file: packages.txt
    - uses: r-lib/actions/setup-pandoc@v2
      with:
        pandoc-version: '2.19.2' # The pandoc version to download (if necessary) and use.
    - name: Build PDF
      run: |
        mkdir ./output
        make README.pdf
    - uses: actions/upload-artifact@v3
      with:
        name: output
        path: output    
